#!/usr/bin/env python
"""
ingest_authoritative.py

Loads the canonical per-table metadata records built by metadata_builder/
(metadata_builder/output/metadata/*.json) into the pycsw catalogue
(p_pycsw.records), so the portal can search and display authoritative
a_* datasets alongside whatever ingest_minio.py / ingest_postgis.py load.

p_pycsw.records is the single source of truth for portal search, QGIS
MetaSearch, and the LLM agent - the agent no longer reads
metadata_builder/output/metadata/*.json directly. Those files are still this
script's INPUT (metadata_builder/build.py's canonical output), but every
GEMINI2 field and column description they contain is also written into the
metadata_json JSONB column here (see build_metadata_json()), structured as
{gemini, columns} - deliberately just those two sections; technical details
that don't serve the portal/agent read path (capabilities, discovery_hints,
provenance, quality, build) stay out of metadata_json. A handful of existing
p_pycsw.records/pycsw-schema columns (topicategory, lineage, time_begin,
time_end, title_alternate) are also populated from the same gemini values.
Run scripts/migrate_add_metadata_json.py once before the first run of this
script, to add schema_name/table_name/metadata_json to p_pycsw.records.

Credentials: read from .env using the same GIS_DB_HOST/PORT/NAME/USER/
PASSWORD/SSLMODE variables as the rest of this project (portal/settings.py's
GIS_DB_CONFIG, catalogue/views.py's _db_connect(), metadata_builder/
extract_schema.py's DB_CONFIG) — not the hardcoded YOUR_DB_* placeholders in
ingest_postgis.py.template, since this project's convention is .env-based
credentials for every script that doesn't ship with the repo pre-filled.

Metadata source: every *.json file in metadata_builder/output/metadata/,
resolved relative to this script's own location (../metadata_builder/output/
metadata), so the same script reads the bundled mock/dev records unmodified
and, once deployed, the real records generated by metadata_builder/build.py
on the production server.

After upserting every record from the current metadata build, any
p_pycsw.records row with source = 'authoritative' whose identifier is not
backed by any file in this build is deleted (trimmed) - this removes records
for tables that have been dropped or renamed since the last ingest, so
p_pycsw.records never drifts from what's actually in metadata_builder/output/
metadata/. Trimming is skipped in --dry-run mode (no database connection to
compare against).

Usage:
    python scripts/ingest_authoritative.py
    python scripts/ingest_authoritative.py --dry-run   # map + print, no DB writes

If GIS_DB_USER is unset or still the YOUR_DB_USER placeholder (e.g. on a dev
laptop with no VPN access to the real PostGIS server), the script
automatically runs in dry-run mode instead of failing outright.
"""
import argparse
import json
import sys
from pathlib import Path

from dotenv import load_dotenv
import os

try:
    import psycopg2
except ImportError:  # pragma: no cover - dry-run only works without this
    psycopg2 = None

SCRIPT_DIR = Path(__file__).resolve().parent
BASE_DIR = SCRIPT_DIR.parent
METADATA_DIR = BASE_DIR / 'metadata_builder' / 'output' / 'metadata'

load_dotenv(BASE_DIR / '.env', override=True)

# Same env vars / defaults as portal/settings.py's GIS_DB_CONFIG and
# metadata_builder/extract_schema.py's DB_CONFIG.
DB_CONFIG = {
    'host': os.environ.get('GIS_DB_HOST', 'gisdb.systra.info'),
    'port': os.environ.get('GIS_DB_PORT', '5432'),
    'dbname': os.environ.get('GIS_DB_NAME', 'uk_irl'),
    'user': os.environ.get('GIS_DB_USER', ''),
    'password': os.environ.get('GIS_DB_PASSWORD', ''),
    'sslmode': os.environ.get('GIS_DB_SSLMODE', 'require'),
}

DEFAULT_UK_LICENCE = 'Open Government Licence'

# p_pycsw.records also has a handful of columns (typename, schema, xml,
# insert_date) that this project's field mapping doesn't specify but that
# the existing ingest_postgis.py.template treats as required. Filled in
# with fixed, descriptive defaults so this script's INSERTs stay valid
# regardless of the exact NOT NULL constraints on the live table; the xml
# column stores the full canonical JSON record for provenance, mirroring
# how ingest_postgis.py.template stuffs a JSON STAC item into the same column.
# (metadata_json below is the new, properly-typed, structured counterpart -
# xml is left as-is; nothing here removes or changes its existing role.)
RECORD_TYPENAME = 'dataset'
RECORD_SCHEMA = 'metadata_builder/authoritative'


def _is_db_unconfigured():
    # Same placeholder check as catalogue/views.py's _is_gis_db_mock().
    return not DB_CONFIG['user'] or DB_CONFIG['user'] == 'YOUR_DB_USER'


def _bbox_to_wkt(bbox):
    """Build a WKT polygon from a WGS84 bbox dict {xmin, ymin, xmax, ymax}."""
    if not bbox:
        return None
    try:
        xmin, ymin, xmax, ymax = bbox['xmin'], bbox['ymin'], bbox['xmax'], bbox['ymax']
    except (KeyError, TypeError):
        return None
    return (
        f'POLYGON(({xmin} {ymin},{xmin} {ymax},'
        f'{xmax} {ymax},{xmax} {ymin},{xmin} {ymin}))'
    )


def _build_anytext(data, organisation):
    """
    Rich searchable text blob — this is what the portal's ILIKE search
    (catalogue/views.py::_search_db_directly) matches against.

    Concatenates title, abstract, keywords, topic_category, organisation,
    schema/table names, and every column's name and description - not just
    table-level fields, so a search for a column-level concept (e.g. a
    specific attribute name) can still find the table.
    """
    columns = data.get('columns') or []
    parts = [
        data.get('title', ''),
        data.get('description', ''),
        ' '.join(data.get('keywords', []) or []),
        data.get('topic_category') or '',
        organisation,
        data.get('schema', ''),
        data.get('table', ''),
    ]
    parts.extend(c.get('name') or '' for c in columns)
    parts.extend(c.get('description') or '' for c in columns)
    return ' '.join(p for p in parts if p)


def load_metadata_files():
    """Every canonical *.json record built by metadata_builder/build.py."""
    if not METADATA_DIR.exists():
        print(f'{METADATA_DIR} does not exist - run metadata_builder/build.py first.', file=sys.stderr)
        sys.exit(1)
    files = sorted(METADATA_DIR.glob('*.json'))
    if not files:
        print(f'No .json files found in {METADATA_DIR} - run metadata_builder/build.py first.', file=sys.stderr)
        sys.exit(1)
    return files


PLACEHOLDER_COLUMN_DESCRIPTION = 'Source attribute; its precise meaning has not yet been documented.'


def _blank_to_none(value):
    """
    Recursively turns '' (and whitespace-only strings) into None, anywhere
    inside a dict/list. Used on the whole 'gemini' section per the cleanup
    spec: no empty strings, no "N/A"/"Not stated" placeholders - just null.
    """
    if isinstance(value, str):
        return value if value.strip() else None
    if isinstance(value, dict):
        return {key: _blank_to_none(v) for key, v in value.items()}
    if isinstance(value, list):
        return [_blank_to_none(v) for v in value]
    return value


def build_metadata_json(data):
    """
    Builds the structured JSONB payload for p_pycsw.records.metadata_json:
    {gemini, columns} only - no technical/capabilities/discovery_hints/
    provenance/quality/build sections; those live in the 'xml' column's full
    dump already, or aren't needed by the portal/agent read path this column
    serves. This is the agent's read path in place of the standalone
    metadata_builder/output/metadata/*.json file.
    """
    publisher = data.get('publisher') or {}
    geometry = data.get('geometry') or {}
    columns = data.get('columns') or []
    dataset_reference_date = data.get('dataset_reference_date') or {}

    licence_name = publisher.get('licence_name')
    licence_url = publisher.get('licence_url')
    if licence_name and licence_url:
        use_constraints = f'{licence_name} — {licence_url}'
    else:
        use_constraints = licence_name or licence_url or None

    gemini = {
        'title': data.get('title'),
        'abstract': data.get('description'),
        'alternative_title': data.get('alternative_title'),
        'topic_category': data.get('topic_category'),
        'keywords': data.get('keywords') or [],
        'temporal_extent': data.get('temporal_extent'),
        'dataset_reference_date': dataset_reference_date.get('date'),
        'dataset_reference_date_type': dataset_reference_date.get('date_type'),
        'lineage': data.get('lineage'),
        'responsible_organisation': publisher.get('organisation'),
        'resource_locator': publisher.get('source_url'),
        'unique_identifier': data.get('identifier'),
        'bounding_box': geometry.get('bbox_wgs84'),
        'spatial_reference_system': geometry.get('crs'),
        'limitations_on_public_access': data.get('limitations_on_public_access'),
        'use_constraints': use_constraints,
        'spatial_resolution': data.get('spatial_resolution'),
        'conformity': data.get('conformity'),
        'metadata_language': data.get('metadata_language'),
        'dataset_language': data.get('dataset_language'),
        'metadata_point_of_contact': data.get('metadata_point_of_contact'),
        'frequency_of_update': data.get('frequency_of_update'),
        'gemini_tier': data.get('gemini_tier'),
        'missing_mandatory_fields': data.get('missing_mandatory_fields') or [],
    }
    gemini = _blank_to_none(gemini)

    column_list = []
    for col in columns:
        description = col.get('description')
        if not description or description == PLACEHOLDER_COLUMN_DESCRIPTION:
            description = None
        column_list.append({
            'name': col.get('name'),
            'type': col.get('data_type'),
            'description': description,
        })

    return {'gemini': gemini, 'columns': column_list}


def build_record(data):
    """
    Map one canonical metadata_builder JSON record onto p_pycsw.records
    columns. Returns (record_dict, skip_reason) — record_dict is None when
    skip_reason is set.
    """
    title = (data.get('title') or '').strip()
    if not title:
        return None, 'missing title'

    schema = data.get('schema', '')
    table = data.get('table', '')
    identifier = data.get('identifier') or f'{schema}/{table}'

    publisher = data.get('publisher') or {}
    geometry = data.get('geometry') or {}

    organisation = publisher.get('organisation') or ''
    licence_name = publisher.get('licence_name') or DEFAULT_UK_LICENCE
    official_url = publisher.get('source_url') or ''
    geometry_type = geometry.get('type') or ''
    crs = geometry.get('crs') or ''
    row_count = data.get('row_count')

    metadata_json = build_metadata_json(data)
    gemini_section = metadata_json.get('gemini') or {}
    temporal_extent = gemini_section.get('temporal_extent') or {}

    record = {
        'identifier': identifier,
        'typename': RECORD_TYPENAME,
        'schema': RECORD_SCHEMA,
        'xml': json.dumps(data, default=str),
        'title': title,
        'abstract': data.get('description', '') or '',
        'keywords': ', '.join(data.get('keywords', []) or []),
        'publisher': organisation,
        'creator': organisation,
        'organization': organisation,
        'accessconstraints': licence_name,
        'mdsource': official_url,
        'type': 'dataset',
        'format': f'PostGIS/{geometry_type}' if geometry_type else 'PostGIS',
        'wkt_geometry': _bbox_to_wkt(geometry.get('bbox_wgs84')),
        'distancevalue': str(row_count) if row_count is not None else '',
        'distanceuom': geometry_type,
        'crs': crs,
        'source': 'authoritative',
        'links': official_url,
        'schema_name': schema,
        'table_name': table,
        'metadata_json': json.dumps(metadata_json, default=str),
        # Task 2: existing p_pycsw.records/pycsw-schema columns, populated
        # from the same metadata_json.gemini values rather than recomputed
        # separately, so they can never drift from what metadata_json shows.
        'topicategory': gemini_section.get('topic_category'),
        'lineage': gemini_section.get('lineage'),
        'time_begin': temporal_extent.get('begin'),
        'time_end': temporal_extent.get('end'),
        'title_alternate': gemini_section.get('alternative_title'),
    }
    record['anytext'] = _build_anytext(data, organisation)
    return record, None


UPSERT_SQL = """
    INSERT INTO p_pycsw.records (
        identifier, typename, schema, mdsource, insert_date, xml,
        anytext, title, abstract, keywords, type, format,
        source, organization, creator, publisher,
        links, crs, accessconstraints, wkt_geometry,
        distancevalue, distanceuom,
        schema_name, table_name, metadata_json,
        topicategory, lineage, time_begin, time_end, title_alternate
    )
    VALUES (
        %(identifier)s, %(typename)s, %(schema)s, %(mdsource)s, NOW(), %(xml)s,
        %(anytext)s, %(title)s, %(abstract)s, %(keywords)s, %(type)s, %(format)s,
        %(source)s, %(organization)s, %(creator)s, %(publisher)s,
        %(links)s, %(crs)s, %(accessconstraints)s, %(wkt_geometry)s,
        %(distancevalue)s, %(distanceuom)s,
        %(schema_name)s, %(table_name)s, %(metadata_json)s::jsonb,
        %(topicategory)s, %(lineage)s, %(time_begin)s, %(time_end)s, %(title_alternate)s
    )
    ON CONFLICT (identifier) DO UPDATE SET
        mdsource          = EXCLUDED.mdsource,
        xml               = EXCLUDED.xml,
        anytext           = EXCLUDED.anytext,
        title             = EXCLUDED.title,
        abstract          = EXCLUDED.abstract,
        keywords          = EXCLUDED.keywords,
        type              = EXCLUDED.type,
        format            = EXCLUDED.format,
        source            = EXCLUDED.source,
        organization      = EXCLUDED.organization,
        creator           = EXCLUDED.creator,
        publisher         = EXCLUDED.publisher,
        links             = EXCLUDED.links,
        crs               = EXCLUDED.crs,
        accessconstraints = EXCLUDED.accessconstraints,
        wkt_geometry      = EXCLUDED.wkt_geometry,
        distancevalue     = EXCLUDED.distancevalue,
        distanceuom       = EXCLUDED.distanceuom,
        schema_name       = EXCLUDED.schema_name,
        table_name        = EXCLUDED.table_name,
        metadata_json     = EXCLUDED.metadata_json,
        topicategory      = EXCLUDED.topicategory,
        lineage           = EXCLUDED.lineage,
        time_begin        = EXCLUDED.time_begin,
        time_end          = EXCLUDED.time_end,
        title_alternate   = EXCLUDED.title_alternate
    RETURNING (xmax = 0) AS inserted
"""


def trim_stale_authoritative_records(cur, conn, current_identifiers):
    """
    Deletes p_pycsw.records rows with source = 'authoritative' whose
    identifier is not backed by any file in the current metadata build -
    tables that have been dropped, renamed, or moved out of the a_* schemas
    since the last ingest. Uses '<> ALL(array)' rather than 'NOT IN (...)':
    psycopg2 adapts a Python list to a Postgres array cleanly, whereas an
    empty tuple passed to 'IN ()' is a SQL syntax error - this stays safe
    even in the (currently unreachable, load_metadata_files() already exits
    if empty) case of zero identifiers.
    """
    if not current_identifiers:
        print('\nTrim step skipped: no identifiers found in this build (nothing to compare against).')
        return 0
    try:
        cur.execute(
            "DELETE FROM p_pycsw.records "
            "WHERE source = 'authoritative' AND identifier <> ALL(%s) "
            "RETURNING identifier",
            (current_identifiers,),
        )
        removed = [row[0] for row in cur.fetchall()]
        conn.commit()
    except Exception as exc:
        conn.rollback()
        print(f'\nTrim step FAILED: {exc}')
        return 0

    if removed:
        print(f'\nTrimmed {len(removed)} stale authoritative record(s):')
        for identifier in removed:
            print(f'    - {identifier}')
    else:
        print('\nNo stale authoritative records found to trim.')
    return len(removed)


def ingest(dry_run):
    files = load_metadata_files()

    conn = cur = None
    if not dry_run:
        conn = psycopg2.connect(**DB_CONFIG)
        cur = conn.cursor()

    total = inserted = updated = skipped = failed = 0
    # Every identifier seen in this build, regardless of skip/failure status -
    # a table that exists but is currently poorly documented (e.g. missing
    # title) should not have its existing p_pycsw.records row trimmed away.
    seen_identifiers = []

    print(f'Found {len(files)} metadata file(s) in {METADATA_DIR}')
    if dry_run:
        print('Running in DRY-RUN mode - no database writes will be made.\n')
    print()

    for i, path in enumerate(files, 1):
        total += 1
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
        except Exception as exc:
            failed += 1
            print(f'[{i}/{len(files)}] {path.name}: FAILED - could not parse JSON ({exc})')
            continue

        schema = data.get('schema', '?')
        table = data.get('table', '?')
        seen_identifiers.append(data.get('identifier') or f'{schema}/{table}')

        record, skip_reason = build_record(data)
        if record is None:
            skipped += 1
            print(f'[{i}/{len(files)}] {schema}/{table}: SKIP - {skip_reason}')
            continue

        if dry_run:
            print(f'[{i}/{len(files)}] {schema}/{table}: OK (dry-run)')
            print(f'    identifier   : {record["identifier"]}')
            print(f'    title        : {record["title"]}')
            print(f'    organisation : {record["organization"]}')
            print(f'    licence      : {record["accessconstraints"]}')
            print(f'    format       : {record["format"]}')
            print(f'    crs          : {record["crs"]}')
            print(f'    row_count    : {record["distancevalue"] or "unknown"}')
            print(f'    wkt_geometry : {record["wkt_geometry"] or "(no bbox available)"}')
            print(f'    mdsource     : {record["mdsource"] or "(no official URL)"}')
            print(f'    keywords     : {record["keywords"]}')
            print(f'    gemini_tier  : {data.get("gemini_tier")}')
            print()
            continue

        try:
            cur.execute(UPSERT_SQL, record)
            was_inserted = cur.fetchone()[0]
            conn.commit()
            if was_inserted:
                inserted += 1
                print(f'[{i}/{len(files)}] {schema}/{table}: OK - INSERT')
            else:
                updated += 1
                print(f'[{i}/{len(files)}] {schema}/{table}: OK - UPDATE')
        except Exception as exc:
            failed += 1
            conn.rollback()
            print(f'[{i}/{len(files)}] {schema}/{table}: FAILED - {exc}')

    if dry_run:
        print('\nTrim step skipped in dry-run mode (no database connection to compare against).')
        deleted = 0
    else:
        deleted = trim_stale_authoritative_records(cur, conn, seen_identifiers)

    if cur:
        cur.close()
    if conn:
        conn.close()

    return total, inserted, updated, deleted, skipped, failed


def main():
    parser = argparse.ArgumentParser(
        description='Load metadata_builder/output/metadata/*.json records into p_pycsw.records.'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Read and map every metadata file and print the result, without connecting to the database.',
    )
    args = parser.parse_args()

    dry_run = args.dry_run
    if not dry_run and _is_db_unconfigured():
        print(
            'GIS_DB_USER is not configured (still the YOUR_DB_USER placeholder or unset) - '
            'falling back to --dry-run. Set GIS_DB_HOST/PORT/NAME/USER/PASSWORD in .env and '
            'ensure VPN/network access to the real PostGIS server to perform a live ingest.\n'
        )
        dry_run = True

    total, inserted, updated, deleted, skipped, failed = ingest(dry_run)

    print(f"""
-----------------------------
Authoritative ingestion {'(dry-run) ' if dry_run else ''}complete
-----------------------------
Total processed  : {total}
Inserted         : {inserted}{' (n/a in dry-run)' if dry_run else ''}
Updated          : {updated}{' (n/a in dry-run)' if dry_run else ''}
Deleted (trimmed): {deleted}{' (n/a in dry-run)' if dry_run else ''}
Skipped          : {skipped}
Failed           : {failed}
-----------------------------
""")

    sys.exit(1 if failed else 0)


if __name__ == '__main__':
    main()
