#!/usr/bin/env python
"""
ingest_authoritative.py

Loads the canonical per-table metadata records built by metadata_builder/
(metadata_builder/output/metadata/*.json) into the pycsw catalogue
(p_pycsw.records), so the portal can search and display authoritative
a_* datasets alongside whatever ingest_minio.py / ingest_postgis.py load.

Credentials: read from .env using the same GIS_DB_HOST/PORT/NAME/USER/
PASSWORD/SSLMODE variables as the rest of this project (portal/settings.py's
GIS_DB_CONFIG, catalogue/views.py's _db_connect(), metadata_builder/
extract_schema.py's DB_CONFIG) — not the hardcoded YOUR_DB_* placeholders in
ingest_postgis.py.template, since this project's convention is .env-based
credentials for every script that doesn't ship with the repo pre-filled.

Metadata source: every *.json file in metadata_builder/output/metadata/,
resolved relative to this script's own location (../metadata_builder/output/
metadata), so the same script reads the bundled mock/dev records unmodified
and, once deployed, the real records generated by metadata_builder/build.py
on the production server.

Usage:
    python scripts/ingest_authoritative.py
    python scripts/ingest_authoritative.py --dry-run   # map + print, no DB writes

If GIS_DB_USER is unset or still the YOUR_DB_USER placeholder (e.g. on a dev
laptop with no VPN access to the real PostGIS server), the script
automatically runs in dry-run mode instead of failing outright.
"""
import argparse
import json
import sys
from pathlib import Path

from dotenv import load_dotenv
import os

try:
    import psycopg2
except ImportError:  # pragma: no cover - dry-run only works without this
    psycopg2 = None

SCRIPT_DIR = Path(__file__).resolve().parent
BASE_DIR = SCRIPT_DIR.parent
METADATA_DIR = BASE_DIR / 'metadata_builder' / 'output' / 'metadata'

load_dotenv(BASE_DIR / '.env', override=True)

# Same env vars / defaults as portal/settings.py's GIS_DB_CONFIG and
# metadata_builder/extract_schema.py's DB_CONFIG.
DB_CONFIG = {
    'host': os.environ.get('GIS_DB_HOST', 'gisdb.systra.info'),
    'port': os.environ.get('GIS_DB_PORT', '5432'),
    'dbname': os.environ.get('GIS_DB_NAME', 'uk_irl'),
    'user': os.environ.get('GIS_DB_USER', ''),
    'password': os.environ.get('GIS_DB_PASSWORD', ''),
    'sslmode': os.environ.get('GIS_DB_SSLMODE', 'require'),
}

DEFAULT_UK_LICENCE = 'Open Government Licence'

# p_pycsw.records also has a handful of columns (typename, schema, xml,
# insert_date) that this project's field mapping doesn't specify but that
# the existing ingest_postgis.py.template treats as required. Filled in
# with fixed, descriptive defaults so this script's INSERTs stay valid
# regardless of the exact NOT NULL constraints on the live table; the xml
# column stores the full canonical JSON record for provenance, mirroring
# how ingest_postgis.py.template stuffs a JSON STAC item into the same column.
RECORD_TYPENAME = 'dataset'
RECORD_SCHEMA = 'metadata_builder/authoritative'


def _is_db_unconfigured():
    # Same placeholder check as catalogue/views.py's _is_gis_db_mock().
    return not DB_CONFIG['user'] or DB_CONFIG['user'] == 'YOUR_DB_USER'


def _bbox_to_wkt(bbox):
    """Build a WKT polygon from a WGS84 bbox dict {xmin, ymin, xmax, ymax}."""
    if not bbox:
        return None
    try:
        xmin, ymin, xmax, ymax = bbox['xmin'], bbox['ymin'], bbox['xmax'], bbox['ymax']
    except (KeyError, TypeError):
        return None
    return (
        f'POLYGON(({xmin} {ymin},{xmin} {ymax},'
        f'{xmax} {ymax},{xmax} {ymin},{xmin} {ymin}))'
    )


def _build_anytext(data, organisation):
    """
    Rich searchable text blob — this is what the portal's ILIKE search
    (catalogue/views.py::_search_db_directly) matches against.
    """
    parts = [
        data.get('title', ''),
        data.get('description', ''),
        ', '.join(data.get('keywords', []) or []),
        organisation,
        data.get('schema', ''),
        data.get('table', ''),
    ]
    return ' '.join(p for p in parts if p)


def load_metadata_files():
    """Every canonical *.json record built by metadata_builder/build.py."""
    if not METADATA_DIR.exists():
        print(f'{METADATA_DIR} does not exist - run metadata_builder/build.py first.', file=sys.stderr)
        sys.exit(1)
    files = sorted(METADATA_DIR.glob('*.json'))
    if not files:
        print(f'No .json files found in {METADATA_DIR} - run metadata_builder/build.py first.', file=sys.stderr)
        sys.exit(1)
    return files


def build_record(data):
    """
    Map one canonical metadata_builder JSON record onto p_pycsw.records
    columns. Returns (record_dict, skip_reason) — record_dict is None when
    skip_reason is set.
    """
    title = (data.get('title') or '').strip()
    if not title:
        return None, 'missing title'

    schema = data.get('schema', '')
    table = data.get('table', '')
    identifier = data.get('identifier') or f'{schema}/{table}'

    publisher = data.get('publisher') or {}
    geometry = data.get('geometry') or {}

    organisation = publisher.get('organisation') or ''
    licence_name = publisher.get('licence_name') or DEFAULT_UK_LICENCE
    official_url = publisher.get('source_url') or ''
    geometry_type = geometry.get('type') or ''
    crs = geometry.get('crs') or ''
    row_count = data.get('row_count')

    record = {
        'identifier': identifier,
        'typename': RECORD_TYPENAME,
        'schema': RECORD_SCHEMA,
        'xml': json.dumps(data, default=str),
        'title': title,
        'abstract': data.get('description', '') or '',
        'keywords': ', '.join(data.get('keywords', []) or []),
        'publisher': organisation,
        'creator': organisation,
        'organization': organisation,
        'accessconstraints': licence_name,
        'mdsource': official_url,
        'type': 'dataset',
        'format': f'PostGIS/{geometry_type}' if geometry_type else 'PostGIS',
        'wkt_geometry': _bbox_to_wkt(geometry.get('bbox_wgs84')),
        'distancevalue': str(row_count) if row_count is not None else '',
        'distanceuom': geometry_type,
        'crs': crs,
        'source': 'authoritative',
        'links': official_url,
    }
    record['anytext'] = _build_anytext(data, organisation)
    return record, None


UPSERT_SQL = """
    INSERT INTO p_pycsw.records (
        identifier, typename, schema, mdsource, insert_date, xml,
        anytext, title, abstract, keywords, type, format,
        source, organization, creator, publisher,
        links, crs, accessconstraints, wkt_geometry,
        distancevalue, distanceuom
    )
    VALUES (
        %(identifier)s, %(typename)s, %(schema)s, %(mdsource)s, NOW(), %(xml)s,
        %(anytext)s, %(title)s, %(abstract)s, %(keywords)s, %(type)s, %(format)s,
        %(source)s, %(organization)s, %(creator)s, %(publisher)s,
        %(links)s, %(crs)s, %(accessconstraints)s, %(wkt_geometry)s,
        %(distancevalue)s, %(distanceuom)s
    )
    ON CONFLICT (identifier) DO UPDATE SET
        mdsource          = EXCLUDED.mdsource,
        xml               = EXCLUDED.xml,
        anytext           = EXCLUDED.anytext,
        title             = EXCLUDED.title,
        abstract          = EXCLUDED.abstract,
        keywords          = EXCLUDED.keywords,
        type              = EXCLUDED.type,
        format            = EXCLUDED.format,
        source            = EXCLUDED.source,
        organization      = EXCLUDED.organization,
        creator           = EXCLUDED.creator,
        publisher         = EXCLUDED.publisher,
        links             = EXCLUDED.links,
        crs               = EXCLUDED.crs,
        accessconstraints = EXCLUDED.accessconstraints,
        wkt_geometry      = EXCLUDED.wkt_geometry,
        distancevalue     = EXCLUDED.distancevalue,
        distanceuom       = EXCLUDED.distanceuom
    RETURNING (xmax = 0) AS inserted
"""


def ingest(dry_run):
    files = load_metadata_files()

    conn = cur = None
    if not dry_run:
        conn = psycopg2.connect(**DB_CONFIG)
        cur = conn.cursor()

    total = inserted = updated = skipped = failed = 0

    print(f'Found {len(files)} metadata file(s) in {METADATA_DIR}')
    if dry_run:
        print('Running in DRY-RUN mode - no database writes will be made.\n')
    print()

    for i, path in enumerate(files, 1):
        total += 1
        try:
            data = json.loads(path.read_text(encoding='utf-8'))
        except Exception as exc:
            failed += 1
            print(f'[{i}/{len(files)}] {path.name}: FAILED - could not parse JSON ({exc})')
            continue

        schema = data.get('schema', '?')
        table = data.get('table', '?')

        record, skip_reason = build_record(data)
        if record is None:
            skipped += 1
            print(f'[{i}/{len(files)}] {schema}/{table}: SKIP - {skip_reason}')
            continue

        if dry_run:
            print(f'[{i}/{len(files)}] {schema}/{table}: OK (dry-run)')
            print(f'    identifier   : {record["identifier"]}')
            print(f'    title        : {record["title"]}')
            print(f'    organisation : {record["organization"]}')
            print(f'    licence      : {record["accessconstraints"]}')
            print(f'    format       : {record["format"]}')
            print(f'    crs          : {record["crs"]}')
            print(f'    row_count    : {record["distancevalue"] or "unknown"}')
            print(f'    wkt_geometry : {record["wkt_geometry"] or "(no bbox available)"}')
            print(f'    mdsource     : {record["mdsource"] or "(no official URL)"}')
            print(f'    keywords     : {record["keywords"]}')
            print()
            continue

        try:
            cur.execute(UPSERT_SQL, record)
            was_inserted = cur.fetchone()[0]
            conn.commit()
            if was_inserted:
                inserted += 1
                print(f'[{i}/{len(files)}] {schema}/{table}: OK - INSERT')
            else:
                updated += 1
                print(f'[{i}/{len(files)}] {schema}/{table}: OK - UPDATE')
        except Exception as exc:
            failed += 1
            conn.rollback()
            print(f'[{i}/{len(files)}] {schema}/{table}: FAILED - {exc}')

    if cur:
        cur.close()
    if conn:
        conn.close()

    return total, inserted, updated, skipped, failed


def main():
    parser = argparse.ArgumentParser(
        description='Load metadata_builder/output/metadata/*.json records into p_pycsw.records.'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Read and map every metadata file and print the result, without connecting to the database.',
    )
    args = parser.parse_args()

    dry_run = args.dry_run
    if not dry_run and _is_db_unconfigured():
        print(
            'GIS_DB_USER is not configured (still the YOUR_DB_USER placeholder or unset) - '
            'falling back to --dry-run. Set GIS_DB_HOST/PORT/NAME/USER/PASSWORD in .env and '
            'ensure VPN/network access to the real PostGIS server to perform a live ingest.\n'
        )
        dry_run = True

    total, inserted, updated, skipped, failed = ingest(dry_run)

    print(f"""
-----------------------------
Authoritative ingestion {'(dry-run) ' if dry_run else ''}complete
-----------------------------
Total processed : {total}
Inserted        : {inserted}{' (n/a in dry-run)' if dry_run else ''}
Updated         : {updated}{' (n/a in dry-run)' if dry_run else ''}
Skipped         : {skipped}
Failed          : {failed}
-----------------------------
""")

    sys.exit(1 if failed else 0)


if __name__ == '__main__':
    main()
